version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: hospital-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital
      MYSQL_USER: root
      MYSQL_PASSWORD: Vai@091005#
      
    ports:
      - "3306:3306"
    volumes:
      - hospital-db:/var/lib/mysql

  backend:
    image: hospital-backend
    container_name: hospital-backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hospital
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"

volumes:
  hospital-db:
